name: Activity Box

on:
  schedule:
    - cron: '*/60 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: danglingptr0x0/activity-box@master
        env:
          GH_PAT: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USERNAME: simonSlamka
          GIST_ID: 8ba88bded8b5b5e8423f17ad06ac39d4
