name: Update GitHub Gist with Neko-box!

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Update activity from AniList
        uses: rangerdigital/neko-box@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 01c5960ccda6ca66734286a22f04f9bb
          ANILIST_USERNAME: ${{ secrets.ANILIST_USERNAME }}
